# Generated by Django 2.2.27 on 2022-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.FloatField()),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
